apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "multi-resource-app.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: migrate/migrate:v4.15.2
        command: ["migrate", "-path", "/migrations", "-database", "postgres://..."]